In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import rasterio
from sklearn.model_selection import train_test_split
import statsmodels.api as sm

In [2]:
trad_dir = 'LC08_L2SP_116034_20180509_20200901_02_T1_ST_TRAD_90m_masked.TIF'
B10_dir = 'LC08_L2SP_116034_20180509_20200901_02_T1_ST_B10_90m_masked.TIF'
ndbi_dir = 'LC08_L2SP_116034_20180509_20200901_02_T1_SR_NDBI_90m_masked.TIF'
B1_dir = 'LC08_L2SP_116034_20180509_20200901_02_T1_SR_B1_90m_masked.TIF'
B2_dir = 'LC08_L2SP_116034_20180509_20200901_02_T1_SR_B2_90m_masked.TIF'
B3_dir = 'LC08_L2SP_116034_20180509_20200901_02_T1_SR_B3_90m_masked.TIF'
B4_dir = 'LC08_L2SP_116034_20180509_20200901_02_T1_SR_B4_90m_masked.TIF'
B5_dir = 'LC08_L2SP_116034_20180509_20200901_02_T1_SR_B5_90m_masked.TIF'
B6_dir = 'LC08_L2SP_116034_20180509_20200901_02_T1_SR_B6_90m_masked.TIF'
B7_dir = 'LC08_L2SP_116034_20180509_20200901_02_T1_SR_B7_90m_masked.TIF'

B10 = rasterio.open(B10_dir)
ndbi = rasterio.open(ndbi_dir)
B1 = rasterio.open(B1_dir)
B2 = rasterio.open(B2_dir)
B3 = rasterio.open(B3_dir)
B4 = rasterio.open(B4_dir)
B5 = rasterio.open(B5_dir)
B6 = rasterio.open(B6_dir)
B7 = rasterio.open(B7_dir)

B10_img = B10.read(1)
ndbi_img = ndbi.read(1)
B1_img = B1.read(1)
B2_img = B2.read(1)
B3_img = B3.read(1)
B4_img = B4.read(1)
B5_img = B5.read(1)
B6_img = B6.read(1)
B7_img = B7.read(1)

  GROUP = LEVEL2_SURFACE_REFLECTANCE_PARAMETERS
    REFLECTANCE_MAXIMUM_BAND = 1.602213
    REFLECTANCE_MINIMUM_BAND = -0.199972
    QUANTIZE_CAL_MAX_BAND = 65535
    QUANTIZE_CAL_MIN_BAND = 1
    REFLECTANCE_MULT_BAND = 2.75e-05
    REFLECTANCE_ADD_BAND = -0.2
  END_GROUP = LEVEL2_SURFACE_REFLECTANCE_PARAMETERS
  GROUP = LEVEL2_SURFACE_TEMPERATURE_PARAMETERS
    TEMPERATURE_MAXIMUM_BAND_ST_B10 = 372.999941
    TEMPERATURE_MINIMUM_BAND_ST_B10 = 149.003418
    QUANTIZE_CAL_MAXIMUM_BAND_ST_B10 = 65535
    QUANTIZE_CAL_MINIMUM_BAND_ST_B10 = 1
    TEMPERATURE_MULT_BAND_ST_B10 = 0.00341802
    TEMPERATURE_ADD_BAND_ST_B10 = 149.0
  END_GROUP = LEVEL2_SURFACE_TEMPERATURE_PARAMETERS

In [3]:
REFLECTANCE_MULT_BAND = 2.75e-05
REFLECTANCE_ADD_BAND = -0.2
TEMPERATURE_MULT_BAND_ST_B10 = 0.00341802
TEMPERATURE_ADD_BAND_ST_B10 = 149.0

In [4]:
# print(B10.nodata)
# print(ndbi.nodata)
# print(B2.nodata)

In [5]:
B10_img_masked = np.ma.masked_array(B10_img, mask=(B10_img == B10.nodata))
ndbi_img_masked = np.ma.masked_array(ndbi_img, mask=(ndbi_img == ndbi.nodata))
B1_img_masked = np.ma.masked_array(B1_img, mask=(B1_img == B1.nodata))
B2_img_masked = np.ma.masked_array(B2_img, mask=(B2_img == B2.nodata))
B3_img_masked = np.ma.masked_array(B3_img, mask=(B3_img == B3.nodata))
B4_img_masked = np.ma.masked_array(B4_img, mask=(B4_img == B4.nodata))
B5_img_masked = np.ma.masked_array(B5_img, mask=(B5_img == B5.nodata))
B6_img_masked = np.ma.masked_array(B6_img, mask=(B6_img == B6.nodata))
B7_img_masked = np.ma.masked_array(B7_img, mask=(B7_img == B7.nodata))

# plt.imshow(B1_img_masked,cmap='gray')

In [6]:
# plt.imshow(B10_img_masked,cmap='gray')

In [7]:
# x = B10_img_masked*TEMPERATURE_MULT_BAND_ST_B10 + TEMPERATURE_ADD_BAND_ST_B10
# # x = B10_img_masked*TEMPERATURE_MULT_BAND_ST_B10 + TEMPERATURE_ADD_BAND_ST_B10 - 273.15
# y_ndbi = ndbi_img_masked
# y1 = B1_img_masked*REFLECTANCE_MULT_BAND +REFLECTANCE_ADD_BAND
# y2 = B2_img_masked*REFLECTANCE_MULT_BAND +REFLECTANCE_ADD_BAND
# y3 = B3_img_masked*REFLECTANCE_MULT_BAND +REFLECTANCE_ADD_BAND
# y4 = B4_img_masked*REFLECTANCE_MULT_BAND +REFLECTANCE_ADD_BAND
# y5 = B5_img_masked*REFLECTANCE_MULT_BAND +REFLECTANCE_ADD_BAND
# y6 = B6_img_masked*REFLECTANCE_MULT_BAND +REFLECTANCE_ADD_BAND
# y7 = B7_img_masked*REFLECTANCE_MULT_BAND +REFLECTANCE_ADD_BAND

In [8]:
# fig = plt.figure(figsize=(20, 15)) 

# plt.subplot(421)
# plt.scatter(x, y1)
# plt.ylabel("B1")
 
# plt.subplot(422)
# plt.scatter(x, y2)
# plt.ylabel("B2")

# plt.subplot(423)
# plt.scatter(x, y3)
# plt.ylabel("B3")

# plt.subplot(424)
# plt.scatter(x, y4)
# plt.ylabel("B4")

# plt.subplot(425)
# plt.scatter(x, y5)
# plt.ylabel("B5")

# plt.subplot(426)
# plt.scatter(x, y6)
# plt.ylabel("B6")

# plt.subplot(427)
# plt.scatter(x, y7)
# plt.ylabel("B7")

# plt.subplot(428)
# plt.scatter(x, y_ndbi)
# plt.ylabel("NDBI")

# plt.show()

In [9]:
# fig = plt.figure(figsize=(20, 15)) 

# plt.subplot(421)
# plt.scatter(x, 1-y1)
# plt.ylabel("B1")
 
# plt.subplot(422)
# plt.scatter(x, 1-y2)
# plt.ylabel("B2")

# plt.subplot(423)
# plt.scatter(x, 1-y3)
# plt.ylabel("B3")

# plt.subplot(424)
# plt.scatter(x, 1-y4)
# plt.ylabel("B4")

# plt.subplot(425)
# plt.scatter(x, 1-y5)
# plt.ylabel("B5")

# plt.subplot(426)
# plt.scatter(x, 1-y6)
# plt.ylabel("B6")

# plt.subplot(427)
# plt.scatter(x, 1-y7)
# plt.ylabel("B7")

# plt.subplot(428)
# plt.scatter(x, y_ndbi)
# plt.ylabel("NDBI")

# plt.show()

In [10]:
# df = pd.DataFrame(((np.ma.masked_array(B10_img, mask=(B10_img == B10.nodata)))*TEMPERATURE_MULT_BAND_ST_B10 + TEMPERATURE_ADD_BAND_ST_B10))
# df

In [11]:
B10_1d = np.ravel(((np.ma.masked_array(B10_img, mask=(B10_img == B10.nodata)))*TEMPERATURE_MULT_BAND_ST_B10 + TEMPERATURE_ADD_BAND_ST_B10 - 273.15), order='C')
B1_1d = np.ravel(((np.ma.masked_array(B1_img, mask=(B1_img == B1.nodata)))*REFLECTANCE_MULT_BAND +REFLECTANCE_ADD_BAND), order='C')
B2_1d = np.ravel(((np.ma.masked_array(B2_img, mask=(B2_img == B2.nodata)))*REFLECTANCE_MULT_BAND +REFLECTANCE_ADD_BAND), order='C')
B3_1d = np.ravel(((np.ma.masked_array(B3_img, mask=(B3_img == B3.nodata)))*REFLECTANCE_MULT_BAND +REFLECTANCE_ADD_BAND), order='C')
B4_1d = np.ravel(((np.ma.masked_array(B4_img, mask=(B4_img == B4.nodata)))*REFLECTANCE_MULT_BAND +REFLECTANCE_ADD_BAND), order='C')
B5_1d = np.ravel(((np.ma.masked_array(B5_img, mask=(B5_img == B5.nodata)))*REFLECTANCE_MULT_BAND +REFLECTANCE_ADD_BAND), order='C')
B6_1d = np.ravel(((np.ma.masked_array(B6_img, mask=(B6_img == B6.nodata)))*REFLECTANCE_MULT_BAND +REFLECTANCE_ADD_BAND), order='C')
B7_1d = np.ravel(((np.ma.masked_array(B7_img, mask=(B7_img == B7.nodata)))*REFLECTANCE_MULT_BAND +REFLECTANCE_ADD_BAND), order='C')

# df = pd.DataFrame(np.ravel(((np.ma.masked_array(B10_img, mask=(B10_img == B10.nodata)))*TEMPERATURE_MULT_BAND_ST_B10 + TEMPERATURE_ADD_BAND_ST_B10), order='C'))
df = pd.DataFrame({'B10': B10_1d, 'B1': B1_1d,'B2': B2_1d,'B3': B3_1d,'B4': B4_1d, 
                   'B5': B5_1d,'B6': B6_1d,'B7': B7_1d})
df = df.dropna()
df

,B10,B1,B2,B3,B4,B5,B6,B7
249,18.757416,0.030147,0.037242,0.076100,0.058060,0.278225,0.175980,0.107312
250,19.188087,0.036335,0.042440,0.085560,0.064028,0.335068,0.205707,0.121365
251,18.497647,0.034052,0.040873,0.079427,0.061663,0.323600,0.183158,0.105222
252,17.646560,0.025803,0.030532,0.061965,0.041423,0.305367,0.146280,0.071837
253,17.680740,0.025968,0.030340,0.064880,0.041368,0.324012,0.153678,0.074175
...,...,...,...,...,...,...,...,...
137638,20.357050,0.029405,0.030450,0.056273,0.033227,0.383412,0.160470,0.069252
137639,20.145132,0.028415,0.029735,0.053605,0.031825,0.369717,0.152880,0.065348
137640,19.922961,0.027177,0.028470,0.053385,0.030862,0.360175,0.148645,0.063175
137641,20.692016,0.027920,0.029295,0.053275,0.032320,0.334572,0.147270,0.065843
138038,19.796494,0.024317,0.026957,0.055943,0.032183,0.348295,0.146610,0.064082

In [15]:
Y = df.drop(['B10'], axis=1)
Y

              B1        B2        B3        B4        B5        B6        B7
249     0.030147  0.037242  0.076100  0.058060  0.278225  0.175980  0.107312
250     0.036335  0.042440  0.085560  0.064028  0.335068  0.205707  0.121365
251     0.034052  0.040873  0.079427  0.061663  0.323600  0.183158  0.105222
252     0.025803  0.030532  0.061965  0.041423  0.305367  0.146280  0.071837
253     0.025968  0.030340  0.064880  0.041368  0.324012  0.153678  0.074175
...          ...       ...       ...       ...       ...       ...       ...
137638  0.029405  0.030450  0.056273  0.033227  0.383412  0.160470  0.069252
137639  0.028415  0.029735  0.053605  0.031825  0.369717  0.152880  0.065348
137640  0.027177  0.028470  0.053385  0.030862  0.360175  0.148645  0.063175
137641  0.027920  0.029295  0.053275  0.032320  0.334572  0.147270  0.065843
138038  0.024317  0.026957  0.055943  0.032183  0.348295  0.146610  0.064082

[74771 rows x 7 columns]

In [16]:
X = df[{'B10'}]
X

              B10
249     18.757416
250     19.188087
251     18.497647
252     17.646560
253     17.680740
...           ...
137638  20.357050
137639  20.145132
137640  19.922961
137641  20.692016
138038  19.796494

[74771 rows x 1 columns]

In [17]:
# for b0, 상수항 추가
x_data1 = sm.add_constant(X, has_constant = "add")

# OLS 검정
multi_model = sm.OLS(Y, x_data1)
fitted_multi_model = multi_model.fit()
fitted_multi_model.summary()

C:\Users\SPINS\anaconda3\envs\bob\lib\site-packages\statsmodels\tsa\tsatools.py:142: FutureWarning: In a future version of pandas all arguments of concat except for the argument 'objs' will be keyword-only
  x = pd.concat(x[::order], 1)

ValueError: shapes (74771,7) and (74771,7) not aligned: 7 (dim 1) != 74771 (dim 0)

In [14]:
# x_train, x_test, y_train, y_test = train_test_split(X, Y, test_size = 0.2, random_state = 42)

NameError: name 'X' is not defined